/**
 * Supported entity types for dataset generation
 */
export enum EntityType {
  PERSON = 'person',
  COMPANY = 'company',
  CUSTOM = 'custom',
}

/**
 * Supported relationship types for dataset generation
 */
export enum RelationshipType {
  ONE_TO_MANY = 'one-to-many',
  MANY_TO_MANY = 'many-to-many',
}

/**
 * Supported custom pattern types
 */
export enum PatternType {
  REGEX = 'regex',
  ENUM = 'enum',
  FORMAT = 'format',
  RANGE = 'range',
}

/**
 * Supported locales for data generation
 */
export enum SupportedLocale {
  EN = 'en',
  FR = 'fr',
  DE = 'de',
  ES = 'es',
  JA = 'ja',
}

/**
 * Address information
 */
export interface Address {
  street: string;
  city: string;
  state: string;
  postalCode: string;
  country: string;
}

/**
 * Relationship definition for dataset entities
 */
export interface RelationshipDefinition {
  references: string;
  type: RelationshipType;
  nullable?: boolean;
}

/**
 * Entity definition for dataset generation
 */
export interface EntityDefinition {
  count: number;
  type: EntityType;
  fields?: string[];
  relationships?: Record<string, RelationshipDefinition>;
}

/**
 * Dataset schema definition
 */
export interface DatasetSchema {
  entities: Record<string, EntityDefinition>;
}

/**
 * Range pattern value
 */
export interface RangePattern {
  min: number;
  max: number;
  precision?: number;
}

/**
 * Custom pattern definition
 */
export interface CustomPattern {
  type: PatternType;
  value: string | string[] | RangePattern;
}

/**
 * Seed configuration for reproducible generation
 */
export interface SeedConfiguration {
  seed?: number;
  autoGenerated: boolean;
  seedString?: string;
}
